### ISSUE TITLE
有没有计划增加 SS功能  和 2.4G 5G 分开管理

### ISSUE THREAD

**Issue by vmvz** [crackself/Gargoyle-Luci#1]
以前用梅林固件, 今天买了个4300, 尝试刷了你的做固件,感觉非常好.

就是想问问有没有 ss[ssr]功能 

以及

2.4G 5G 分开管理

例如, 5G的密码 隐藏 等等 不一样

谢谢

**Comment by crackself** [comment]
SS有的，9月份的版本内置；WiFi分开管理没有，或许到石像鬼官方提建议添加更好

**Comment by crackself** [comment]
2017-11-25 版本，内置shadowsocks
